### ISSUE TITLE
abyss-pe optimalization for big plant genome

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/abyss#328] opened 2020-04-21 22:40 UTC
`abyss-pe` is finished. I get this log file:

```
Best scaffold N50 is 3620 at n=5 s=1000.

n	n:1000	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
51.44e6	164446	41828	164446	1000	1000	2262	3620	5985	5529	134218	514.3e6	n=5 s=1000
MergeContigs -v  -k64 -o lculinaris-8.tigmint.arcs.fa lculinaris-8.tigmint.fa lculinaris-8.tigmint.arcs.path
Reading `lculinaris-8.tigmint.fa'...
Read 51441652 sequences. Using 20.8 GB of memory.
Reading `lculinaris-8.tigmint.arcs.path'...
Read 1337 paths. Using 20.8 GB of memory.
The minimum coverage of single-end contigs is inf.
The minimum coverage of merged contigs is inf.
n	n:200	L50	min	N75	N50	N25	E-size	max	sum	name
51.44e6	2486829	317039	200	285	610	2919	2482	134218	1.261e9	lculinaris-8.tigmint.arcs.fa
ln -sf lculinaris-8.tigmint.arcs.fa lculinaris-scaffolds.fa
PathOverlap --overlap -v  -k64 --dot lculinaris-7.dot lculinaris-7.path >lculinaris-8.dot
Reading `lculinaris-7.dot'...
Reading `lculinaris-7.path'...
ln -sf lculinaris-8.dot lculinaris-scaffolds.dot
abyss-fac -G4000000000  lculinaris-unitigs.fa lculinaris-contigs.fa lculinaris-scaffolds.fa |tee lculinaris-stats.tab
n	n:500	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
52.03e6	527283	123511	527283	500	500	844	1487	2643	2510	67386	652.2e6	lculinaris-unitigs.fa
51.47e6	440753	83610	440753	500	500	988	2375	4130	3611	134218	689.8e6	lculinaris-contigs.fa
51.44e6	422737	70361	422737	500	500	987	2627	4955	4299	134218	688.7e6	lculinaris-scaffolds.fa
time user=143.46s system=23.92s elapsed=168.16s cpu=99% memory=3 job=abyss-fac -G4000000000 lculinaris-unitigs.fa lculinaris-contigs.fa 
time user=0.00s system=0.00s elapsed=168.16s cpu=0% memory=0 job=
ln -sf lculinaris-stats.tab lculinaris-stats
tr '\t' , <lculinaris-stats.tab >lculinaris-stats.csv
abyss-tabtomd lculinaris-stats.tab >lculinaris-stats.md
```

How could I optimalize the `abyss-pe` for I get longer sequencies in the scaffold fasta file? I used this paramers: `abyss-pe k=64 name=lculinaris v=-v j=192 B=550G H=4 kc=2 G=4000000000` Should I try kc=3 and kc=4? k=64 is good because I choose this with `ntCard`.

**Comment by lcoombe** [comment] 2020-04-21 22:43
So are you asking how to optimize the contiguity (N50) of the overall assembly? The answer is slightly different for different stages of the assembly.

In general, to optimize the ABySS assembly itself (before Tigmint/ARCS) we sweep on `k` values, and try a couple `kc` as well -- I usually try `kc=3, 4`. Personally, I'd try a couple of values around that `k` value suggested by ntCard. You could run the assembly with those parameters up to the unitig or even scaffold stage, and choose the best one to move forward with with Tigmint and ARCS.

**Comment by hidvegin** [comment] 2020-04-21 23:02
I used the `ntCard` with k32, k64, k96 and k128. I set the k-mer values for the test. After the test I get the F1 and F0 numbers. Based on the highest F0 number (largest unique k-mers) I choose the k64.  How could I set the ntCard for suggest to me a couple of k-mer values? Also, should I test the Illumina PE reads and 10x Genomics linked reads together in the ntCard?

**Comment by sjackman** [comment] 2020-04-22 16:47
What's the ploidy and heterozygosity of your genome?
I suggest using [GenomeScope](http://qb.cshl.edu/genomescope/) with the ntCard histograms to pick _k_. Even then, you'll want to try a few values of _k_ with ABySS.

**Comment by hidvegin** [comment] 2020-04-22 16:54
Hi @sjackman:

My genome is diploid but I do not know the heterozygosity. Could I determine the heterozygosity of my genome with `ntCard`? I have got the hist files (k32, k64, k96 and k128) from `ntCard`.

**Comment by sjackman** [comment] 2020-04-22 18:59
Great! Diploid and het of 0.17% are good for ABySS.
Mode _k_-mer coverage of 100 is high. I'd suggest using a larger value of _k_ that reduces mode _k_-mer coverage to ~20.

**Comment by hidvegin** [comment] 2020-04-22 19:07
Do you suggest larger value of `k` in ntCard? If yes, here is the results (k96 and k128):
k96: http://genomescope.org/analysis.php?code=MdOI9X5yi3diroh9sMWT
k128: http://genomescope.org/analysis.php?code=QuuacIxXBrEovdutx33Z

**Comment by sjackman** [comment] 2020-04-22 19:58
_k_=128 has a mode _k_-mer coverage of 20 and looks good to me.
I'd suggest trying assembling three values of _k_: 128, something smaller, and something larger, and see how it affects contiguity.

**Comment by sjackman** [comment] 2020-04-22 20:00
Perhaps values of _k_ that give mode _k_-mer depth of ~15, ~20, and ~25 or ~30.

**Comment by hidvegin** [comment] 2020-04-22 20:34
Ok, I will try with k112,120,128,136,144 in `ntCard`. After that I can pick the right values of k which give k-mer depth of ~15 - ~30. Should I try the value of `kc` at 2, 3 and 4 or enough if I choose only 3 and 4?

**Comment by sjackman** [comment] 2020-04-23 17:29
kc=3 and kc=4 should be sufficient. Based on these plots _k= 120, 120, 136 looks good.

**Comment by sjackman** [comment] 2020-04-23 17:31
You hope to see a peak in NG50 / Busco completeness (or whatever your preferred target metric is) for the middle value of _k_, that is _k_=128. If the peak is either _k_=120 or _k_=128, keep searching in that direction.

Closing this issue, but feel free to post your results or follow-up questions.

**Closed** 2020-04-23 17:31 UTC
Labels: question

**Comment by hidvegin** [comment] 2020-04-23 17:32
Thank you for your answer. I will try your suggestions.

**Comment by hidvegin** [comment] 2020-05-05 07:14
I tried abyss-pe with k120, k128 and k136. I tried without scaffold with the linked reads, this results for only the Illumina PE 150bp reads. For k136 I get an error message.
This is the results for k120:

```
n	n:500	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
11.4e6	1602860	359966	1602860	500	500	789	1398	2798	2176	29243	1.916e9	lculinaris-unitigs.fa
10.01e6	1284682	211374	1284682	500	500	901	2497	4869	3548	42918	1.972e9	lculinaris-contigs.fa
9964249	1247305	184732	1247305	500	500	900	2769	5595	4033	42918	1.971e9	lculinaris-scaffolds.fa
```

k128:

```
n	n:500	L50	LG50	NG50	min	N75	N50	N25	E-size	max	sum	name
9959811	1723659	413852	1723659	500	500	774	1308	2471	1950	28567	1.98e9	lculinaris-unitigs.fa
8587960	1364518	230144	1302252	515	500	876	2370	4616	3364	39903	2.033e9	lculinaris-contigs.fa
8533308	1319540	197069	1257274	515	500	876	2651	5426	3911	48103	2.032e9	lculinaris-scaffolds.fa
```

k136:

```
abyss-stack-size 65536 abyss-bloom-dbg -k136 -q3 --kc=3 -v -b550G -H4 -j192  ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_2.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_2.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_2.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz ~/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_2.fq.gz  > lculinaris-1.fa
Running with max stack size of 65536 KB: abyss-bloom-dbg -k136 -q3 --kc=3 -v -b550G -H4 -j192 /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_1.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L2A_2.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_1.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L3A_2.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_1.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4A_2.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_1.fq.gz /home/fk8jybr/szeged/fk8jybr/input/Illumina_trimmed/LC002_L4B_2.fq.gz
Error: k is 136 and must be no more than 128. You can recompile ABySS to increase this limit.
/big/home/fk8jybr/.linuxbrew/bin/abyss-pe:538: recipe for target 'lculinaris-1.fa' failed
make: *** [lculinaris-1.fa] Error 1
```

**Comment by schutzekatze** [comment] 2020-05-05 08:50
ABySS imposes a limit on the size of kmers and the k parameter (for memory efficiency) which is 128 by default. If you compile ABySS yourself, you can increase this limit by specifying the --enable-maxk parameter when running configure (e.g. `./configure --enable-maxk=256` for 256 size).

If you are using ABySS from a package manager like Linuxbrew, this limit is set by the package manger itself as it compiles the binaries. As far as I'm aware, you cannot configure it in that case, although @sjackman should be able to advise on that.

**Comment by hidvegin** [comment] 2020-05-05 11:11
Yes, I used linuxbrew for install ABySS. The question is that should I use `k` more than 128 or not, based on the results with `k=120` and `k=128` . At scaffold with `k=120` the N50 is higher than `k=128` but the n value is lower at `k=120`. Should I check some values between `k=120` and `k=128`? Example. `k=122, 124, 126`? Now I used `kc=3` with this `k` values. Should I check `kc=4` also with `k=120` and `k=128`?

**Comment by sjackman** [comment] 2020-05-05 18:47
The assembly is not terribly contiguous, and that can be challenging to troubleshoot. Are you assembling *Lens culinaris*? This paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5865747) says that genome is ~4 GB, but GenomeScope is estimating 3 Gbp. Do you know the origin of the discrepancy?

In your GenomeScope plot, there is not good separation between the orange error k-mers and the yellow unique sequence. I'd suggest trying smaller values of _k_ that give better separation, based on these assembly results. For reference, good separation might look something like this:

![genomescope](https://user-images.githubusercontent.com/291551/81103526-006c7c80-8ec6-11ea-8e96-7357a4486e03.png)

**Comment by hidvegin** [comment] 2020-05-05 20:34
Yes, I am assembling the _Lens culinaris_ genome. I think the reason of the difference that I used an different species of _Lens culinaris_ from the reference.  I tried in `ntCard` the `k=72`,` k=80`, `k=88`, `k=96` and `k=104` with only 150 bp Illumina PE reads and with together the PE and linked reads. Here is the resaults:

only PE reads
k=72: [](http://genomescope.org/analysis.php?code=lrwirxeb0Q2lzbZGgyEh)
k=80: [](http://genomescope.org/analysis.php?code=vDxWemQyMxigRL7LVTLx)
k=88: [](http://genomescope.org/analysis.php?code=7AovOK3fYnCgEXlYVYmi)
k=96: [](http://genomescope.org/analysis.php?code=CKyRfCevSPnVO1nVnPoP)
k=104: [](http://genomescope.org/analysis.php?code=F7uVCkXTetl1PYjsncVP)

together the PE and linked reads
k=72: [](http://genomescope.org/analysis.php?code=zqbSVZWpNF1ONlblsxor)
k=80: [](http://genomescope.org/analysis.php?code=BuuiF6FuhXOVTmmV7fEB)
k=88: [](http://genomescope.org/analysis.php?code=EJC3Spx4M2yhd8AXynzT)
k=96: [](http://genomescope.org/analysis.php?code=bFnni49c0OWui6d2jd3T)
k=104: [](http://genomescope.org/analysis.php?code=h7WRktEuRLzZfoxAtAnP)

**Comment by sjackman** [comment] 2020-05-05 21:05
The plateau between the orange error k-mers and yellow unique k-mers is really wide and doesn't seem to go away for any value of k. It's troubling. Have you run FastQC on this data?

The repeat content also seems high, but that's not too terribly surprising for a plant genome.

**Comment by hidvegin** [comment] 2020-05-06 14:01
Here is the FastQC results of the dataset.

Linked reads:

Library 1: [https://unidebhu-my.sharepoint.com/:u:/g/personal/hidvegi-norbert_mailbox_unideb_hu/EQD8p1xFsD1DpDhadByJ93MBR0uLtEWfSL6CSgCAc5qdQQ?e=SzGNBv](url)

**Comment by sjackman** [comment] 2020-05-06 17:12
The Illumina PE libraries have some red flags that the linked reads don't have.
Have you trimmed Illumina adapters using a tool such as `fastp`, `cutadapt`, or `trimmomatic`?
Which linked reads technology are you using, 10x Chromium? Which software tool did you use to remove the barcodes?
Sequence duplications levels seem high. The LR libraries report ~75% unique sequence, and the PE libraries report ~65% unique sequence.
PCR-free library prep is best for de novo assembly. Are these PCR-free libraries?
Since the linked read libraries have better FastQC reports, I'd suggest trying assembling just the linked read libraries.
Have you tried running Supernova on the linked reads?

**Comment by hidvegin** [comment] 2020-05-07 13:13
I used NEBNext® Ultra II DNA Library Prep Kit for the Illumina PE reads. I trimmed the adapters with `TrimGalore`. I used 10x Chromium for linked reads. I used `longranger` for remove barcodes and `TrimGalore` for remove the Illumina adapters. For this de novo sequencing I used 150x Illumina PE reads, 60x linked reads and 30x PacBio long reads. I think that I will make a contigs with Illumina PE reads and scaffolding with linked reads in `abyss-pe`. After that fill the gaps in the scaffold with the PacBio long reads with `LINKS`. Is it challenging or impossiple?

**Comment by lcoombe** [comment] 2020-05-07 16:05
Hi @hidvegin - Just a note about your assembly plan. I would suggest running the linked read scaffolding with ARCS as late as you can in the assembly process -- we find it is most effective when the input draft assembly is more contiguous. So, you could run LINKS prior to the Tigmint/ARCS step.
Also, just to clarify LINKS is a long-read scaffolder, not a gap-filler. If you are looking for a gap-filler with long reads, take a look at our tool Cobbler/RAILS (https://github.com/bcgsc/RAILS)

**Comment by sjackman** [comment] 2020-05-07 16:41
With 30x long read depth, I'd suggest trying an assembly of the PacBio long reads on their own with Canu (and other long read assemblers like Flye), and then correcting and scaffolding the long read assembly using Tigmint (which runs ARCS for you).

I'd definitely recommend trying an assembly of the Linked Reads using Supernova. If you're feeling experimental, you may wish to try scaffolding using the linked reads using our in development tool Physlr. https://github.com/bcgsc/physlr

What does an ntCard + Genomescope profile of only the linked reads look like? I want to see if the large plateau goes away.

**Comment by sjackman** [comment] 2020-05-07 16:42
Are the PacBio HiFi (CCS) reads or single pass reads?

**Comment by sjackman** [comment] 2020-05-07 16:43
Ryan Wick wrote an article recently comparing long read assemblers for prokaryote assembly, but many of these assemblers scale to larger genomes. https://github.com/rrwick/Long-read-assembler-comparison

**Comment by hidvegin** [comment] 2020-05-07 20:21
@lcoombe and @sjackman 
Thank you for your comments. I will try it. Here is the results of ntCard and Genomescope:

k64: http://genomescope.org/analysis.php?code=8Hkd8Q2V8T7Zl8EkGV5o
k72: http://genomescope.org/analysis.php?code=2A4WGEToLOjVfwndT6dY
k80: http://genomescope.org/analysis.php?code=fEFEtfXytIKnkQi5bw7w

Higher than k80 was bad for the linked reads because Genomescope has failed with unconverged.
I used single pass reads on the PacBio Sequel Platform.

**Comment by sjackman** [comment] 2020-05-08 20:14
There's quite a large plateau in the linked reads as well. I was hoping that it was unique to the PE reads. `uniq:60%` suggests that the genome is quite repetitive, which could be the root cause that this genome is proving challenging to assemble. Just as an anecdotal comparison, a large 10 GB conifer genome that I assembled had `uniq:92%`. A recent whole genome duplication in lentil (since human cultivation for example) could explain this repeat content. In that case, long reads (or possibly linked reads) may assemble better than short reads.

**Comment by hidvegin** [comment] 2020-05-08 20:25
Summary: You suggest that I should make an assembly with the PacBio long reads (example. with canu or flye) and after that fill the gaps or improve this draft genome with linked reads and PE reads. 
Are there any gap-filler which can improve the draft PacBio genome with linked and PE reads?

**Comment by sjackman** [comment] 2020-05-08 20:55
Yes, I'd suggest assembling the PacBio long reads, and then correct errors and scaffold using Tigmint (and possibly Physlr if you're feeling experimental).

@lcoombe @warrenlr Where is the diagram of various software tools from the Birol lab that René created? Here's a list of these tools: http://www.birollab.ca/software

There's Cobbler/RAILS for gap filling with long sequences, and Sealer for gap falling with short reads (which is included with ABySS). I don't believe that there's a tool specifically for gap filling using linked reads. If you assembled the linked reads with say Supernova, you could potentially gap fill using those contigs with Cobbler/RAILS.

**Comment by lcoombe** [comment] 2020-05-08 21:00
There's a couple of diagrams summarizing our group's tools on the main page of our website: http://www.birollab.ca/

**Comment by hidvegin** [comment] 2020-05-10 17:43
@sjackman and @lcoombe 

Thank you for your suggestions.

**Comment by hidvegin** [comment] 2020-07-12 08:09
Hi @sjackman and @lcoombe,

I have got the draft scaffold sequences from PacBio long reads and 10x Genomics linked reads which generated with `canu `and `tigmint`. I would like to use `abyss-sealer` for fill the gaps between the scaffold sequences with the linked reads and Illumina PE reads.

I tried this parameters:

`abyss-sealer --print-flanks -b100G -j80 -k96 -k128 -o lculinaris -S $HOME/output/tigmint/contig_trimmed/draft.tigmint.arcs.fa $HOME/output/trimmed/10x/LC001_trimmed.fq.gz $HOME/output/trimmed/10x/LC002_trimmed.fq.gz $HOME/output/trimmed/10x/LC003_trimmed.fq.gz $HOME/output/trimmed/10x/LC004_trimmed.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_2.fq.gz`

abyss-sealer is running since about 12 hours and generated the flanks_1.fa, flanks_2.fa, log.txt, merged.fa and scaffold.fa but all of this files are empty. I do not know is it normal or abyss-sealer is stucked?

**Comment by hidvegin** [comment] 2020-07-13 16:24
It seems normal. abyss-sealer is finished the job. This is the output file:

```
Finding flanks
8087 gaps found
8087 flanks extracted

Building bloom filter
Starting K run with k = 96
Flanks inserted into k run = 8087
100 gaps closed so far
200 gaps closed so far
300 gaps closed so far
385 unique gaps closed for k96
No start/goal kmer: 4717
No path: 1457
Unique path: 371
Multiple paths: 14
Too many paths: 82
Too many branches: 0
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Max cost exceeded: 1446
Exceeded mem limit: 0
Skipped: 0
7702 flanks left
k96 run complete
Total gaps closed so far = 385

Building bloom filter
Starting K run with k = 128
Flanks inserted into k run = 7702
0 unique gaps closed for k128
No start/goal kmer: 7702
No path: 0
Unique path: 0
Multiple paths: 0
Too many paths: 0
Too many branches: 0
Too many path/path mismatches: 0
Too many path/read mismatches: 0
Contains cycle: 0
Max cost exceeded: 0
Exceeded mem limit: 0
Skipped: 0
7702 flanks left
k128 run complete
Total gaps closed so far = 385

K sweep complete
Creating new scaffold with gaps closed...
New scaffold complete
Gaps closed = 385
4.76073%
```

Should I try more k-mer values? I think the "385 gaps closed" is not a good result.

**Comment by lcoombe** [comment] 2020-07-13 17:32
Hi @hidvegin,

Yes, I would suggest running a more extensive k-sweep. If I'm using 10X Genomics linked reads for gap sealing, I often run k values from 75-125 (step 10).
If you want the run to go faster, you can pre-make the Bloom filters for each `k`, and specify the paths to `abyss-sealer` -- that way you can build the Bloom filters in parallel (if you have the appropriate resources).

**Comment by hidvegin** [comment] 2020-07-14 18:37
Thanks @lcoombe. I will try it based on your comment.

**Comment by hidvegin** [comment] 2020-07-21 08:22
Hi @lcoombe,

I generated the Bloom filters for k values from 34-124 (step 10). This was the paramater:

`abyss-bloom build -vv -k34 -j80 -b200G -l2 k34.bloom $HOME/output/tigmint/contig_trimmed/draft.tigmint.arcs.fa $HOME/output/trimmed/10x/LC001_trimmed.fq.gz $HOME/output/trimmed/10x/LC002_trimmed.fq.gz $HOME/output/trimmed/10x/LC003_trimmed.fq.gz $HOME/output/trimmed/10x/LC004_trimmed.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_2.fq.gz`

Now, I would like to use the pre-make Bloom filters to abyss-sealer. This is the code which I would like to use:

`abyss-sealer -j80 --print-flanks -k34 -k44 -k54 -k64 -k74 -k84 -k94 -k104 -k114 -k124 -o lculinaris -S $HOME/output/tigmint/contig_trimmed/draft.tigmint.arcs.fa -i $HOME/output/abyss_bloom/k34.bloom -i $HOME/output/abyss_bloom/k44.bloom -i $HOME/output/abyss_bloom/k54.bloom -i $HOME/output/abyss_bloom/k64.bloom -i $HOME/output/abyss_bloom/k74.bloom -i $HOME/output/abyss_bloom/k84.bloom -i $HOME/output/abyss_bloom/k94.bloom -i $HOME/output/abyss_bloom/k104.bloom -i $HOME/output/abyss_bloom/k114.bloom -i $HOME/output/abyss_bloom/k124.bloom $HOME/output/trimmed/10x/LC001_trimmed.fq.gz $HOME/output/trimmed/10x/LC002_trimmed.fq.gz $HOME/output/trimmed/10x/LC003_trimmed.fq.gz $HOME/output/trimmed/10x/LC004_trimmed.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L2A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L3A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4A_trimmed_2.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_1.fq.gz $HOME/output/trimmed/Illumina/LC002_L4B_trimmed_2.fq.gz`

But I got this error:

```
abyss-sealer: input FASTA/FASTQ args should be omitted when using pre-built Bloom filters (-i) for all k-mer sizes
Try `abyss-sealer --help' for more information.
```

What should I do exactly?

**Comment by lcoombe** [comment] 2020-07-21 15:33
Hi @hidvegin,

SInce you have pre-built the Bloom filters, you do not need to include the read fastq files in your `abyss-sealer` command. Try removing those `fastq` arguments.
