### ISSUE TITLE
ABySS v2.0.2 - [XXX-3.dist] Error 1

### ISSUE THREAD

**Issue by machadodj** [bcgsc/abyss#148] opened 2017-03-04 15:53 UTC
# Introduction

I'm currently trying to assemble short sequence reads from Illumina HiSeq2500 that have been filtered and trimmed using a variety of quality control tools (e.g., FastUniq, HTQC, Trimmomatic, NextClip).

Mate pair libraries were prepared with different protocols (i.e., Gel Free, 3kb, 5kb, 8kb, 10kb). After quality controls, many reads are separated and treated as single-end or paired-end reads. In the end, I have one single-end file, two paired-end files (one left and one right), and 20 mate paired-end files (10 left and 10 right).

After trying multiple strategies and tweaking with ABySS parameters, I still can't assemble these data. As in #146, ABySS gives the error `make: *** [genome-3.dist] Error 1` before it stops, but in my case the FR percentage is not higher than the FF percantage (see details bellow).

# This are the last 10 lines of the standard output and standart error
`==> abyss202test.o264600 <==`
`########################################################################`
`PBS Epilogue: Wed Mar 1 02:54:03 EST 2017`
`Job ID: 264600.login00.halcyon.local`
`Limits: neednodes=1:ppn=24,nodes=1:ppn=24,vmem=999gb,walltime=777:00:00`
`Resources: cput=5124778:22:10,mem=1034514212kb,vmem=1039322020kb,walltime=156:18:30`
`Account:`
`Exit Value: 2`
`########################################################################`

`==> abyss202test.e264600 <==`
`Singleton 91470746 26.6%`
`FR 16728487 4.87%`
`RF 985 0.000287%`
`FF 11597 0.00338%`
`Different 70687721 20.6%`
`Total 343237788`
`FR Stats mean: 209.1 median: 185 sd: 85.38 n: 16726873 min: 21 max: 891 ignored: 2599`
`▁▄▅██▇▆▅▄▃▃▂▂▁▁▁▁_____`
`make: *** [lpe-3.dist] Error 1`
`make: *** Deleting file 'lpe-3.dist'`

# More details here
Please check the following files for the standart output, partial standart error (last 1,000 lines), and PBS script (which includes details of the lybraries/ modeules used):
- [standart_outout.txt](https://github.com/bcgsc/abyss/files/818732/standart_outout.txt)
- [partial_standart_error.txt](https://github.com/bcgsc/abyss/files/818735/partial_standart_error.txt)
- [pbs_script.txt](https://github.com/bcgsc/abyss/files/818737/pbs_script.txt)

# Conclusion
I would like some clarification on this error and tips on how to proceed. Perhaps more information is needed to track this problem, but this post is already too long as it is. Please let me know if there is any additional information you might need.

Thank you very much for your time and attention.

**Comment by sjackman** [comment] 2017-03-05 20:11
I don't see any obvious cause of the error in your log file. I'd suggest adding `pe-sam` to your `abyss-pe` command line to save the `.sam.gz` file, so that you can run outside of your HPC scheduling system the DistanceEst command that's failing, to aid troubleshooting.
```
abyss-pe … pe-sam
DistanceEst -v  -j24 -k31 -l40 -s1000 -n10   -o lpe-3.dist lpe-3.hist lpe-3.sam.gz
```

**Comment by benvvalk** [comment] 2017-03-06 17:30
Thanks, @sjackman.

@machadodj:  Thanks for providing a detailed description with log files, etc! I noticed a couple of error messages in the STDERR log you provided.  This lines is probably the root cause of your problems:
```
sort: cannot create temporary file in `/scratch/torque/264600.login00.halcyon.local': No such file or directory
```

You should be able change the temporary directory that is used by `sort` by exporting `TMPDIR` at the top of your job script, e.g.
```
export TMPDIR=/var/tmp
```

**Comment by sjackman** [comment] 2017-03-06 17:32
Good eyes, Ben! 👀

**Comment by benvvalk** [comment] 2017-03-06 17:38
@sjackman:  Thanks! (I got a good chuckle out of the googly eyes, btw.)

**Comment by sjackman** [comment] 2017-03-06 18:01
The eyes should follow your cursor like `xeyes`.

**Comment by machadodj** [comment] 2017-03-14 20:00
I would like to start by thanking @sjackman and @benvvalk for their comments.


Taking their comments into account, I specified the TMPDIR at the beginning of my PBS script:

`export TMPDIR=/lustre/scratch/dmachado`

I also added the pe-sam argument to my abyss-pe command line:

`/home/dmachado/sw/ABySS_202/bin/abyss-pe -C k${kmer_size} k=${kmer_size} np=24 j=24 n=10 v=-v name=scaf${kmer_size} lib="lpe" mp="mp1 mp2 mp3 mp4 mp5 mp6 mp7 mp8 mp9 mp10" lpe="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/pe_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/pe_2.fq" mp1="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_03kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_03kb_2.fq" mp2="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_05kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_05kb_2.fq" mp3="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_08kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_08kb_2.fq" mp4="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_10kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_10kb_2.fq" mp5="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_03kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_03kb_2.fq" mp6="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_free_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/mp_free_2.fq" mp7="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_05kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_05kb_2.fq" mp8="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_08kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_08kb_2.fq" mp9="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_10kb_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_10kb_2.fq" mp10="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_free_1.fq /group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/un_free_2.fq" se="/group/janieslab/dmachado/161010_uncc164/07_pterribilis/01_abyss/se.fq" B=990G H=10 kc=3 v=-v pe-sam`

 However, the assembly creashed at what seems to be the same point it was crashing before. Here are the last 20 lines of the standart error:

> Read 683000000 alignments. Hash load: 4 / 32 = 0.125 using 422 kB.
> Read 684000000 alignments. Hash load: 8 / 32 = 0.25 using 422 kB.
> Read 685000000 alignments. Hash load: 8 / 32 = 0.25 using 422 kB.
> Read 686000000 alignments. Hash load: 8 / 32 = 0.25 using 422 kB.
> Mapped 266328386 of 686475576 reads (38.8%)
> Mapped 263164154 of 686475576 reads uniquely (38.3%)
> Read 686475576 alignments
> Mateless           0
> Unaligned  164338183  47.9%
> Singleton   91470824  26.6%
> FR          16728464  4.87%
> RF               985  0.000287%
> FF             11597  0.00338%
> Different   70687735  20.6%
> Total      343237788
> FR Stats mean: 209.1 median: 185 sd: 85.38 n: 16726850 min: 21 max: 891 ignored: 2599
>         ▁▄▅██▇▆▅▄▃▃▂▂▁▁▁▁_____
> make: *** [lpe-3.sam.gz] Error 2
> make: *** Deleting file 'lpe-3.sam.gz'
> make: *** [lpe-3.sam.gz] Deleting file 'lpe-3.hist'

The compressed file abyss148.tar.gz (see attached) contains the standard error, standard output, PBS script and list of files in the output directory.

Neither I or the technicians working with me can figure out what is wrong. One suspicion we have is that at some point ABySS is trying more memory than what's available (999GB), which could perhaps be fixed by changing some of the command line arguments, but we are not sure how to proceed and all our tests this far have failed. Therefore, any further input on this issue is gonna be very much appreciated.

Thanks a lot for your attention.

[abyss148.tar.gz](https://github.com/bcgsc/abyss/files/842514/abyss148.tar.gz)

**Comment by sjackman** [comment] 2017-03-14 22:22
Hi, @machadodj. It's the same error message:
```
❯❯❯ grep 'cannot create temporary file' abyss202test.e265667
sort: cannot create temporary file in `/lustre/scratch/dmachado': No such file or directory
```
You can resolve this error by creating the directory `/lustre/scratch/dmachado`.
```
mkdir -p /lustre/scratch/dmachado
```

**Comment by benvvalk** [comment] 2017-12-18 18:31
Closing this issue because it seems to be due to job setup / cluster configuration, rather than ABySS itself.

**Closed by benvvalk** 2017-12-18 18:31 UTC
